version: "3.7"

services:

# ####    mariadb     #### #
  mariadb:
    image: mariadb

    restart: always

    environment:
      # 設置密碼
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       # 設置database
      MYSQL_DATABASE: ${MYSQL_DATABASE}

      # 設置新的用戶(選用)
      # MYSQL_USER: test
      # MYSQL_PASSWORD: test

      # 允許root為空白密碼(不建議)
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes

      # 隨機產生密碼
      # MYSQL_RANDOM_ROOT_PASSWORD:

    # ports:
    #   - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest

    restart: always

    environment:
      # 設置 1 允許連接到任意服務器
      PMA_ARBITRARY: 1

    ports:
      - "${PHPMYADMIN_PORT}:80"

    depends_on:
      - mariadb

# ####    Redis     #### #

  redis:
    image: redis:latest

    restart: always

    ports:
     - "6379:6379"

  redismyadmin:
    image: erikdubbelboer/phpredisadmin

    environment:
      # 服務器主機
      REDIS_1_HOST: ${REDIS_1_HOST}

      # 服務器名稱
      REDIS_1_NAME: ${REDIS_1_NAME}

      # 服務器PORT
      REDIS_1_PORT: ${REDIS_1_PORT}

      # 服務器密碼
      # REDIS_1_AUTH:

      # 設定帳號密碼
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
    ports:
      - "${REDIS_MYADMIN_PORT}:80"

    depends_on:
      - redis

# ####    Gitlab     #### #
  gitlab:
    image: gitlab/gitlab-ce:latest

    restart: always

    hostname: 'localhost'

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'

    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

    ports:
      - "443:443"
      - "80:80"
      - "22:22"

# ####    Drone CI/CD     #### #
  drone-server:
    image: drone/drone:1
    restart: always
    ports:
      - "${DRONESERVER_PORT}:80"
    volumes:
      - /var/lib/drone:/var/lib/drone/
    environment:
      # Github Server: https://github.com
      - DRONE_GITHUB_SERVER=${DRONE_GITHUB_SERVER}
      # Github OAuth Client ID
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      # Github OAuth Client Secret
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}

      # 自動生成SSL證書，並將服務器配置為接受HTTPS請求
      - DRONE_TLS_AUTOCERT=false

      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      # 自架 Drone Server
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      # HTTP or HTTPS
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      # Drone logs
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_DEBUG=true

  drone-agent:
    image: drone/agent:latest
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # drone-server位置
      - DRONE_RPC_HOST=drone-server
      # drone-server
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      # 運行程序可以執行的並發管道數
      - DRONE_RUNNER_CAPACITY=3